CREATE TABLE business_partner
(
    partner_id          NUMBER(19)
                          GENERATED BY DEFAULT ON NULL AS IDENTITY,

    company_id          NUMBER(19)          NOT NULL,
    partner_code        VARCHAR2(30 CHAR)   NOT NULL,
    partner_name        VARCHAR2(100 CHAR)  NOT NULL,
    business_number     VARCHAR2(10 CHAR),
    representative_name VARCHAR2(50 CHAR),
    contact_name        VARCHAR2(50 CHAR),
    phone               VARCHAR2(20 CHAR),
    email               VARCHAR2(254 CHAR),
    postal_code         VARCHAR2(10 CHAR),
    address1            VARCHAR2(200 CHAR),
    address2            VARCHAR2(200 CHAR),

    supplier_yn         CHAR(1 CHAR
) NOT NULL,
    customer_yn           CHAR(1 CHAR)        NOT NULL,

    use_yn                CHAR(1 CHAR)
                          DEFAULT 'Y'         NOT NULL,

    created_at            TIMESTAMP(6)
                          DEFAULT SYSTIMESTAMP NOT NULL,
    created_by            NUMBER(19),

    updated_at            TIMESTAMP(6)
                          DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            NUMBER(19),

    CONSTRAINT pk_business_partner
        PRIMARY KEY (partner_id),

    CONSTRAINT fk_partner_company
        FOREIGN KEY (company_id)
        REFERENCES company (company_id),

    CONSTRAINT fk_partner_created_by
        FOREIGN KEY (created_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT fk_partner_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT ck_partner_supplier_yn
        CHECK (supplier_yn IN ('Y', 'N')),

    CONSTRAINT ck_partner_customer_yn
        CHECK (customer_yn IN ('Y', 'N')),

    CONSTRAINT ck_partner_use_yn
        CHECK (use_yn IN ('Y', 'N')),

    CONSTRAINT ck_partner_role_required
        CHECK (
            supplier_yn = 'Y'
            OR customer_yn = 'Y'
        )
);

CREATE UNIQUE INDEX uq_partner_company_code
    ON business_partner (
        company_id,
        LOWER(TRIM(partner_code))
    );

CREATE UNIQUE INDEX uq_partner_company_business
    ON business_partner (
        CASE WHEN business_number IS NOT NULL
        THEN company_id
        END,
        CASE WHEN business_number IS NOT NULL
        THEN TRIM(business_number)
        END
    );

CREATE INDEX ix_partner_supplier
    ON business_partner (
        company_id,
        supplier_yn,
        use_yn
    );

CREATE INDEX ix_partner_customer
    ON business_partner (
        company_id,
        customer_yn,
        use_yn
    );