CREATE TABLE product
(
    product_id     NUMBER(19)
                     GENERATED BY DEFAULT ON NULL AS IDENTITY,

    company_id     NUMBER(19)          NOT NULL,
    product_code   VARCHAR2(50 CHAR)   NOT NULL,
    product_name   VARCHAR2(100 CHAR)  NOT NULL,

    lot_managed_yn CHAR(1 CHAR
) NOT NULL,
    tax_type         VARCHAR2(20 CHAR)   NOT NULL,
    storage_type     VARCHAR2(20 CHAR)   NOT NULL,

    use_yn           CHAR(1 CHAR)
                     DEFAULT 'Y'         NOT NULL,

    created_at       TIMESTAMP(6)
                     DEFAULT SYSTIMESTAMP NOT NULL,
    created_by       NUMBER(19),

    updated_at       TIMESTAMP(6)
                     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by       NUMBER(19),

    CONSTRAINT pk_product
        PRIMARY KEY (product_id),

    CONSTRAINT fk_product_company
        FOREIGN KEY (company_id)
        REFERENCES company (company_id),

    CONSTRAINT fk_product_created_by
        FOREIGN KEY (created_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT fk_product_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT ck_product_lot_managed
        CHECK (lot_managed_yn IN ('Y', 'N')),

    CONSTRAINT ck_product_tax_type
        CHECK (
            tax_type IN (
                'TAXABLE',
                'TAX_FREE'
            )
        ),

    CONSTRAINT ck_product_storage_type
        CHECK (
            storage_type IN (
                'AMBIENT',
                'CHILLED',
                'FROZEN'
            )
        ),

    CONSTRAINT ck_product_use_yn
        CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_product_company_code
    ON product (
        company_id,
        LOWER(TRIM(product_code))
    );

CREATE INDEX ix_product_company_use
    ON product (
        company_id,
        use_yn
    );