CREATE TABLE product_unit
(
    product_unit_id NUMBER(19)
                      GENERATED BY DEFAULT ON NULL AS IDENTITY,

    product_id      NUMBER(19)      NOT NULL,
    unit_id         NUMBER(19)      NOT NULL,
    conversion_qty  NUMBER(19, 3)   NOT NULL,

    is_base_yn      CHAR(1 CHAR
) NOT NULL,

    use_yn            CHAR(1 CHAR)
                      DEFAULT 'Y'     NOT NULL,

    created_at        TIMESTAMP(6)
                      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by        NUMBER(19),

    updated_at        TIMESTAMP(6)
                      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by        NUMBER(19),

    CONSTRAINT pk_product_unit
        PRIMARY KEY (product_unit_id),

    CONSTRAINT fk_product_unit_product
        FOREIGN KEY (product_id)
        REFERENCES product (product_id),

    CONSTRAINT fk_product_unit_unit
        FOREIGN KEY (unit_id)
        REFERENCES unit (unit_id),

    CONSTRAINT fk_product_unit_created_by
        FOREIGN KEY (created_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT fk_product_unit_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES app_user (app_user_id),

    CONSTRAINT uq_product_unit
        UNIQUE (product_id, unit_id),

    CONSTRAINT ck_product_unit_qty
        CHECK (conversion_qty > 0),

    CONSTRAINT ck_product_unit_base_yn
        CHECK (is_base_yn IN ('Y', 'N')),

    CONSTRAINT ck_product_unit_base_qty
        CHECK (
            is_base_yn = 'N'
            OR conversion_qty = 1
        ),

    CONSTRAINT ck_product_unit_use_yn
        CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_product_unit_base
    ON product_unit (
        CASE WHEN is_base_yn = 'Y'
        THEN product_id
        END
        );

CREATE INDEX ix_product_unit_unit
    ON product_unit (unit_id);