CREATE TABLE warehouse
(
    warehouse_id   NUMBER(19)
    GENERATED BY DEFAULT ON NULL AS IDENTITY,

    company_id     NUMBER(19)          NOT NULL,
    warehouse_code VARCHAR2(30 CHAR)   NOT NULL,
    warehouse_name VARCHAR2(100 CHAR)  NOT NULL,

    postal_code    VARCHAR2(10 CHAR),
    address1       VARCHAR2(200 CHAR),
    address2       VARCHAR2(200 CHAR),
    description    VARCHAR2(200 CHAR),

    use_yn         CHAR(1 CHAR
)
    DEFAULT 'Y'         NOT NULL,

created_at       TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by       NUMBER(19),

updated_at       TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by       NUMBER(19),

CONSTRAINT pk_warehouse
PRIMARY KEY (warehouse_id),

CONSTRAINT fk_warehouse_company
FOREIGN KEY (company_id)
REFERENCES company (company_id),

CONSTRAINT fk_warehouse_created_by
FOREIGN KEY (created_by)
REFERENCES app_user (app_user_id),

CONSTRAINT fk_warehouse_updated_by
FOREIGN KEY (updated_by)
REFERENCES app_user (app_user_id),

CONSTRAINT ck_warehouse_use_yn
CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_warehouse_company_code
    ON warehouse (
        company_id,
        LOWER(TRIM(warehouse_code))
    );

CREATE INDEX ix_warehouse_company_use
    ON warehouse (
        company_id,
        use_yn
    );