CREATE TABLE company
(
    company_id               NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_code             VARCHAR2(30 CHAR)    NOT NULL,
    company_name             VARCHAR2(100 CHAR)   NOT NULL,
    business_registration_no VARCHAR2(10 CHAR),
    representative_name      VARCHAR2(50 CHAR),
    phone                    VARCHAR2(20 CHAR),
    email                    VARCHAR2(254 CHAR),
    postal_code              VARCHAR2(10 CHAR),
    address1                 VARCHAR2(200 CHAR),
    address2                 VARCHAR2(200 CHAR),

    active_yn                CHAR(1 CHAR
)
    DEFAULT 'Y'          NOT NULL,

created_at                 TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by                 NUMBER(19),
updated_at                 TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by                 NUMBER(19),

CONSTRAINT pk_company
PRIMARY KEY (company_id),

CONSTRAINT uq_company_code
UNIQUE (company_code),

CONSTRAINT uq_company_business_no
UNIQUE (business_registration_no),

CONSTRAINT ck_company_active_yn
CHECK (active_yn IN ('Y', 'N'))
);








