/*  db  초기 테이블 작성 */


-- =========================================================
-- SALES_ORDER : 판매주문 헤더
-- =========================================================
CREATE TABLE sales_order (
                             sales_order_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                             company_id NUMBER(19) NOT NULL,
                             order_no VARCHAR2(30 CHAR) NOT NULL,
                             customer_id NUMBER(19) NOT NULL,
                             warehouse_id NUMBER(19) NOT NULL,

                             order_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                             requested_delivery_date DATE,

                             order_status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                             shipment_status VARCHAR2(20 CHAR) DEFAULT 'NOT_SHIPPED' NOT NULL,

                             total_supply_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                             total_tax_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                             total_amount NUMBER(19,2) DEFAULT 0 NOT NULL,

                             memo VARCHAR2(1000 CHAR),

                             confirmed_at TIMESTAMP(6),
                             confirmed_by NUMBER(19),

                             created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                             created_by NUMBER(19) NOT NULL,
                             updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                             updated_by NUMBER(19),

                             CONSTRAINT pk_sales_order
                                 PRIMARY KEY (sales_order_id),

                             CONSTRAINT uq_sales_order_company_no
                                 UNIQUE (company_id, order_no),

                             CONSTRAINT fk_sales_order_company
                                 FOREIGN KEY (company_id)
                                     REFERENCES company (company_id),

                             CONSTRAINT fk_sales_order_customer
                                 FOREIGN KEY (customer_id)
                                     REFERENCES business_partner (partner_id),

                             CONSTRAINT fk_sales_order_warehouse
                                 FOREIGN KEY (warehouse_id)
                                     REFERENCES warehouse (warehouse_id),

                             CONSTRAINT fk_sales_order_confirmed_by
                                 FOREIGN KEY (confirmed_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT fk_sales_order_created_by
                                 FOREIGN KEY (created_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT fk_sales_order_updated_by
                                 FOREIGN KEY (updated_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT ck_sales_order_status
                                 CHECK (order_status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),

                             CONSTRAINT ck_sales_order_shipment_status
                                 CHECK (shipment_status IN ('NOT_SHIPPED', 'PARTIAL', 'SHIPPED', 'CLOSED')),

                             CONSTRAINT ck_sales_order_amount
                                 CHECK (
                                     total_supply_amount >= 0
                                         AND total_tax_amount >= 0
                                         AND total_amount >= 0
                                     )
);

-- =========================================================
-- SALES_ORDER_ITEM : 판매주문 품목
-- 주문 당시 상품·단위·단가·세금 정보를 보존하는 Snapshot
-- =========================================================
CREATE TABLE sales_order_item (
                                  sales_order_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                  sales_order_id NUMBER(19) NOT NULL,
                                  line_no NUMBER(10) NOT NULL,

                                  product_id NUMBER(19) NOT NULL,
                                  product_unit_id NUMBER(19) NOT NULL,

    -- 주문한 거래단위 수량
                                  ordered_qty NUMBER(19,3) NOT NULL,

    -- 주문 당시 1 거래단위가 기준단위로 얼마인지 저장
                                  conversion_qty NUMBER(19,3) NOT NULL,

    -- ordered_qty × conversion_qty
                                  base_ordered_qty NUMBER(19,3) NOT NULL,

    -- 누적 출고 '기준단위' 수량, 최초에는 0
                                  shipped_qty NUMBER(19,3) DEFAULT 0 NOT NULL,

    -- 주문 당시 단가·과세·금액 Snapshot
                                  unit_price NUMBER(19,2) NOT NULL,
                                  tax_type VARCHAR2(20 CHAR) NOT NULL,
                                  supply_amount NUMBER(19,2) NOT NULL,
                                  tax_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                                  total_amount NUMBER(19,2) NOT NULL,

    -- 부분출고 동시성 제어용 번호, 최초 0
                                  version NUMBER(10) DEFAULT 0 NOT NULL,

                                  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                  created_by NUMBER(19) NOT NULL,
                                  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                  updated_by NUMBER(19),

                                  CONSTRAINT pk_sales_order_item
                                      PRIMARY KEY (sales_order_item_id),

    -- 한 주문서에서 1번 품목, 2번 품목처럼 순번은 중복될 수 없다.
                                  CONSTRAINT uq_sales_order_item_line
                                      UNIQUE (sales_order_id, line_no),

                                  CONSTRAINT fk_so_item_sales_order
                                      FOREIGN KEY (sales_order_id)
                                          REFERENCES sales_order (sales_order_id),

                                  CONSTRAINT fk_so_item_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES product (product_id),

                                  CONSTRAINT fk_so_item_product_unit
                                      FOREIGN KEY (product_unit_id)
                                          REFERENCES product_unit (product_unit_id),

                                  CONSTRAINT fk_so_item_created_by
                                      FOREIGN KEY (created_by)
                                          REFERENCES app_user (app_user_id),

                                  CONSTRAINT fk_so_item_updated_by
                                      FOREIGN KEY (updated_by)
                                          REFERENCES app_user (app_user_id),

                                  CONSTRAINT ck_so_item_qty
                                      CHECK (
                                          ordered_qty > 0
                                              AND conversion_qty > 0
                                              AND base_ordered_qty > 0
                                              AND shipped_qty >= 0
                                              AND shipped_qty <= base_ordered_qty
                                          ),

                                  CONSTRAINT ck_so_item_amount
                                      CHECK (
                                          unit_price >= 0
                                              AND supply_amount >= 0
                                              AND tax_amount >= 0
                                              AND total_amount >= 0
                                          ),

                                  CONSTRAINT ck_so_item_tax_type
                                      CHECK (tax_type IN ('TAXABLE', 'TAX_FREE'))
);


-- =========================================================
-- OUTBOUND : 출고 Header
-- 확정된 판매주문을 기준으로 만드는 출고 문서 표지
-- =========================================================
CREATE TABLE outbound (
                          outbound_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                          company_id NUMBER(19) NOT NULL,
                          outbound_no VARCHAR2(30 CHAR) NOT NULL,

    -- 단독 출고는 허용하지 않으므로 반드시 판매주문을 연결한다.
                          sales_order_id NUMBER(19) NOT NULL,
                          warehouse_id NUMBER(19) NOT NULL,

                          outbound_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                          status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                          memo VARCHAR2(1000 CHAR),

                          confirmed_at TIMESTAMP(6),
                          confirmed_by NUMBER(19),

    -- 출고취소는 삭제하지 않고 취소 정보와 상태를 남긴다.
                          cancelled_by NUMBER(19),
                          cancelled_at TIMESTAMP(6),
                          cancel_reason VARCHAR2(500 CHAR),

                          created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          created_by NUMBER(19) NOT NULL,
                          updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          updated_by NUMBER(19),

                          CONSTRAINT pk_outbound
                              PRIMARY KEY (outbound_id),

                          CONSTRAINT uq_outbound_company_no
                              UNIQUE (company_id, outbound_no),

                          CONSTRAINT fk_outbound_company
                              FOREIGN KEY (company_id)
                                  REFERENCES company (company_id),

                          CONSTRAINT fk_outbound_sales_order
                              FOREIGN KEY (sales_order_id)
                                  REFERENCES sales_order (sales_order_id),

                          CONSTRAINT fk_outbound_warehouse
                              FOREIGN KEY (warehouse_id)
                                  REFERENCES warehouse (warehouse_id),

                          CONSTRAINT fk_outbound_confirmed_by
                              FOREIGN KEY (confirmed_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_cancelled_by
                              FOREIGN KEY (cancelled_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_created_by
                              FOREIGN KEY (created_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_updated_by
                              FOREIGN KEY (updated_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT ck_outbound_status
                              CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);




-- =========================================================
-- OUTBOUND_ITEM : 출고 품목
-- 출고 문서 안에서 실제로 어떤 주문 품목을 얼마나 출고하는지 저장
-- =========================================================
CREATE TABLE outbound_item (
                               outbound_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                               outbound_id NUMBER(19) NOT NULL,
                               line_no NUMBER(10) NOT NULL,

    -- 어떤 판매주문 품목을 출고하는지 연결
                               sales_order_item_id NUMBER(19) NOT NULL,

    -- 이번 출고에 선택한 거래단위
    -- 주문단위와 달라도 되지만, 같은 상품의 단위여야 함
    -- 이 관계 검증은 나중에 Service에서 처리
                               product_unit_id NUMBER(19) NOT NULL,

    -- 이번 출고의 거래단위 수량
                               shipped_qty NUMBER(19,3) NOT NULL,

    -- 이번 출고 당시의 단위 환산수량
                               conversion_qty NUMBER(19,3) NOT NULL,

    -- shipped_qty × conversion_qty
    -- 이번 출고의 기준단위 수량
                               base_shipped_qty NUMBER(19,3) NOT NULL,

                               created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               created_by NUMBER(19) NOT NULL,
                               updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               updated_by NUMBER(19),

                               CONSTRAINT pk_outbound_item
                                   PRIMARY KEY (outbound_item_id),

    -- 같은 출고서에서 품목 순번은 중복될 수 없다.
                               CONSTRAINT uq_outbound_item_line
                                   UNIQUE (outbound_id, line_no),

    -- 하나의 출고서에서 같은 판매주문 품목을 두 줄로 나누지 않는다.
                               CONSTRAINT uq_outbound_item_so_item
                                   UNIQUE (outbound_id, sales_order_item_id),

                               CONSTRAINT fk_outbound_item_outbound
                                   FOREIGN KEY (outbound_id)
                                       REFERENCES outbound (outbound_id),

                               CONSTRAINT fk_outbound_item_sales_order_item
                                   FOREIGN KEY (sales_order_item_id)
                                       REFERENCES sales_order_item (sales_order_item_id),

                               CONSTRAINT fk_outbound_item_product_unit
                                   FOREIGN KEY (product_unit_id)
                                       REFERENCES product_unit (product_unit_id),

                               CONSTRAINT fk_outbound_item_created_by
                                   FOREIGN KEY (created_by)
                                       REFERENCES app_user (app_user_id),

                               CONSTRAINT fk_outbound_item_updated_by
                                   FOREIGN KEY (updated_by)
                                       REFERENCES app_user (app_user_id),

                               CONSTRAINT ck_outbound_item_qty
                                   CHECK (
                                       shipped_qty > 0
                                           AND conversion_qty > 0
                                           AND base_shipped_qty > 0
                                       )
);




-- =========================================================
-- OUTBOUND_ITEM_LOT : 출고 품목별 LOT 배정
-- LOT 관리상품일 때만 이 테이블에 행을 만든다.
-- =========================================================
CREATE TABLE outbound_item_lot (
                                   outbound_item_lot_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                   outbound_item_id NUMBER(19) NOT NULL,
                                   lot_id NUMBER(19) NOT NULL,

    -- 해당 LOT에서 실제로 출고하는 기준단위 수량
                                   base_lot_qty NUMBER(19,3) NOT NULL,

                                   created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                   created_by NUMBER(19) NOT NULL,
                                   updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                   updated_by NUMBER(19),

                                   CONSTRAINT pk_outbound_item_lot
                                       PRIMARY KEY (outbound_item_lot_id),

    -- 같은 출고 품목에서 같은 LOT를 두 번 선택할 수 없다.
                                   CONSTRAINT uq_outbound_item_lot
                                       UNIQUE (outbound_item_id, lot_id),

                                   CONSTRAINT fk_outbound_item_lot_outbound_item
                                       FOREIGN KEY (outbound_item_id)
                                           REFERENCES outbound_item (outbound_item_id),

                                   CONSTRAINT fk_outbound_item_lot_lot
                                       FOREIGN KEY (lot_id)
                                           REFERENCES lot (lot_id),

                                   CONSTRAINT fk_outbound_item_lot_created_by
                                       FOREIGN KEY (created_by)
                                           REFERENCES app_user (app_user_id),

                                   CONSTRAINT fk_outbound_item_lot_updated_by
                                       FOREIGN KEY (updated_by)
                                           REFERENCES app_user (app_user_id),

                                   CONSTRAINT ck_outbound_item_lot_qty
                                       CHECK (base_lot_qty > 0)
);



-- =========================================================
-- STOCKTAKE : 재고실사 Header
-- 실사 문서의 기본정보와 확정 상태를 저장
-- =========================================================
CREATE TABLE stocktake (
                           stocktake_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                           company_id NUMBER(19) NOT NULL,
                           stocktake_no VARCHAR2(30 CHAR) NOT NULL,
                           warehouse_id NUMBER(19) NOT NULL,

                           stocktake_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                           status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                           memo VARCHAR2(1000 CHAR),

                           confirmed_at TIMESTAMP(6),
                           confirmed_by NUMBER(19),

                           created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                           created_by NUMBER(19) NOT NULL,
                           updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                           updated_by NUMBER(19),

                           CONSTRAINT pk_stocktake
                               PRIMARY KEY (stocktake_id),

                           CONSTRAINT uq_stocktake_company_no
                               UNIQUE (company_id, stocktake_no),

                           CONSTRAINT fk_stocktake_company
                               FOREIGN KEY (company_id)
                                   REFERENCES company (company_id),

                           CONSTRAINT fk_stocktake_warehouse
                               FOREIGN KEY (warehouse_id)
                                   REFERENCES warehouse (warehouse_id),

                           CONSTRAINT fk_stocktake_confirmed_by
                               FOREIGN KEY (confirmed_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT fk_stocktake_created_by
                               FOREIGN KEY (created_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT fk_stocktake_updated_by
                               FOREIGN KEY (updated_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT ck_stocktake_status
                               CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);



-- =========================================================
-- STOCKTAKE_ITEM : 재고실사 품목
-- 상품 단위 또는 LOT 단위로 전산수량과 실제수량을 기록
-- =========================================================
CREATE TABLE stocktake_item (
                                stocktake_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                stocktake_id NUMBER(19) NOT NULL,
                                line_no NUMBER(10) NOT NULL,

                                product_id NUMBER(19) NOT NULL,

    -- LOT 관리상품: LOT ID 저장
    -- LOT 비관리상품: NULL
                                lot_id NUMBER(19),

    -- 전산상 수량 / 실제 센 수량 / 차이 수량
                                system_qty NUMBER(19,3) NOT NULL,
                                actual_qty NUMBER(19,3) NOT NULL,
                                difference_qty NUMBER(19,3) NOT NULL,

                                reason VARCHAR2(500 CHAR),

                                created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                created_by NUMBER(19) NOT NULL,
                                updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                updated_by NUMBER(19),

                                CONSTRAINT pk_stocktake_item
                                    PRIMARY KEY (stocktake_item_id),

                                CONSTRAINT uq_stocktake_item_line
                                    UNIQUE (stocktake_id, line_no),

    -- 같은 실사 문서에 같은 상품·같은 LOT를 중복 등록하지 않는다.
    -- LOT 비관리상품은 lot_id가 NULL인 상태로 적용한다.
                                CONSTRAINT uq_stocktake_item_product_lot
                                    UNIQUE (stocktake_id, product_id, lot_id),

                                CONSTRAINT fk_stocktake_item_stocktake
                                    FOREIGN KEY (stocktake_id)
                                        REFERENCES stocktake (stocktake_id),

                                CONSTRAINT fk_stocktake_item_product
                                    FOREIGN KEY (product_id)
                                        REFERENCES product (product_id),

                                CONSTRAINT fk_stocktake_item_lot
                                    FOREIGN KEY (lot_id)
                                        REFERENCES lot (lot_id),

                                CONSTRAINT fk_stocktake_item_created_by
                                    FOREIGN KEY (created_by)
                                        REFERENCES app_user (app_user_id),

                                CONSTRAINT fk_stocktake_item_updated_by
                                    FOREIGN KEY (updated_by)
                                        REFERENCES app_user (app_user_id),

                                CONSTRAINT ck_stocktake_item_qty
                                    CHECK (
                                        system_qty >= 0
                                            AND actual_qty >= 0
                                        )
);


