CREATE TABLE app_user
(
    app_user_id   NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    company_id    NUMBER(19)          NOT NULL,
    login_id      VARCHAR2(50 CHAR)   NOT NULL,
    password      VARCHAR2(255 CHAR)  NOT NULL,
    user_name     VARCHAR2(50 CHAR)   NOT NULL,
    email         VARCHAR2(254 CHAR),
    phone         VARCHAR2(20 CHAR),
    position_name VARCHAR2(50 CHAR),

    use_yn        CHAR(1 CHAR
)
    DEFAULT 'Y'         NOT NULL,

created_at      TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by      NUMBER(19),

updated_at      TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by      NUMBER(19),

CONSTRAINT pk_app_user
PRIMARY KEY (app_user_id),

CONSTRAINT fk_app_user_company
FOREIGN KEY (company_id)
REFERENCES company (company_id),

CONSTRAINT ck_app_user_use_yn
CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_app_user_login_norm
    ON app_user (LOWER(TRIM(login_id)));

CREATE INDEX ix_app_user_company
    ON app_user (company_id);