-- =========================================================
-- SALES_ORDER : 판매주문 헤더
-- =========================================================
CREATE TABLE sales_order (
                             sales_order_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                             company_id NUMBER(19) NOT NULL,
                             order_no VARCHAR2(30 CHAR) NOT NULL,
                             customer_id NUMBER(19) NOT NULL,
                             warehouse_id NUMBER(19) NOT NULL,

                             order_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                             requested_delivery_date DATE,

                             order_status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                             shipment_status VARCHAR2(20 CHAR) DEFAULT 'NOT_SHIPPED' NOT NULL,

                             total_supply_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                             total_tax_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                             total_amount NUMBER(19,2) DEFAULT 0 NOT NULL,

                             memo VARCHAR2(1000 CHAR),

                             confirmed_at TIMESTAMP(6),
                             confirmed_by NUMBER(19),

                             created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                             created_by NUMBER(19) NOT NULL,
                             updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                             updated_by NUMBER(19),

                             CONSTRAINT pk_sales_order
                                 PRIMARY KEY (sales_order_id),

                             CONSTRAINT uq_sales_order_company_no
                                 UNIQUE (company_id, order_no),

                             CONSTRAINT fk_sales_order_company
                                 FOREIGN KEY (company_id)
                                     REFERENCES company (company_id),

                             CONSTRAINT fk_sales_order_customer
                                 FOREIGN KEY (customer_id)
                                     REFERENCES business_partner (partner_id),

                             CONSTRAINT fk_sales_order_warehouse
                                 FOREIGN KEY (warehouse_id)
                                     REFERENCES warehouse (warehouse_id),

                             CONSTRAINT fk_sales_order_confirmed_by
                                 FOREIGN KEY (confirmed_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT fk_sales_order_created_by
                                 FOREIGN KEY (created_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT fk_sales_order_updated_by
                                 FOREIGN KEY (updated_by)
                                     REFERENCES app_user (app_user_id),

                             CONSTRAINT ck_sales_order_status
                                 CHECK (order_status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),

                             CONSTRAINT ck_sales_order_shipment_status
                                 CHECK (shipment_status IN ('NOT_SHIPPED', 'PARTIAL', 'SHIPPED', 'CLOSED')),

                             CONSTRAINT ck_sales_order_amount
                                 CHECK (
                                     total_supply_amount >= 0
                                         AND total_tax_amount >= 0
                                         AND total_amount >= 0
                                     )
);