-- =========================================================
-- SALES_ORDER_ITEM : 판매주문 품목
-- 주문 당시 상품·단위·단가·세금 정보를 보존하는 Snapshot
-- =========================================================
CREATE TABLE sales_order_item (
                                  sales_order_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                  sales_order_id NUMBER(19) NOT NULL,
                                  line_no NUMBER(10) NOT NULL,

                                  product_id NUMBER(19) NOT NULL,
                                  product_unit_id NUMBER(19) NOT NULL,

    -- 주문한 거래단위 수량
                                  ordered_qty NUMBER(19,3) NOT NULL,

    -- 주문 당시 1 거래단위가 기준단위로 얼마인지 저장
                                  conversion_qty NUMBER(19,3) NOT NULL,

    -- ordered_qty × conversion_qty
                                  base_ordered_qty NUMBER(19,3) NOT NULL,

    -- 누적 출고 '기준단위' 수량, 최초에는 0
                                  shipped_qty NUMBER(19,3) DEFAULT 0 NOT NULL,

    -- 주문 당시 단가·과세·금액 Snapshot
                                  unit_price NUMBER(19,2) NOT NULL,
                                  tax_type VARCHAR2(20 CHAR) NOT NULL,
                                  supply_amount NUMBER(19,2) NOT NULL,
                                  tax_amount NUMBER(19,2) DEFAULT 0 NOT NULL,
                                  total_amount NUMBER(19,2) NOT NULL,

    -- 부분출고 동시성 제어용 번호, 최초 0
                                  version NUMBER(10) DEFAULT 0 NOT NULL,

                                  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                  created_by NUMBER(19) NOT NULL,
                                  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                  updated_by NUMBER(19),

                                  CONSTRAINT pk_sales_order_item
                                      PRIMARY KEY (sales_order_item_id),

    -- 한 주문서에서 1번 품목, 2번 품목처럼 순번은 중복될 수 없다.
                                  CONSTRAINT uq_sales_order_item_line
                                      UNIQUE (sales_order_id, line_no),

                                  CONSTRAINT fk_so_item_sales_order
                                      FOREIGN KEY (sales_order_id)
                                          REFERENCES sales_order (sales_order_id),

                                  CONSTRAINT fk_so_item_product
                                      FOREIGN KEY (product_id)
                                          REFERENCES product (product_id),

                                  CONSTRAINT fk_so_item_product_unit
                                      FOREIGN KEY (product_unit_id)
                                          REFERENCES product_unit (product_unit_id),

                                  CONSTRAINT fk_so_item_created_by
                                      FOREIGN KEY (created_by)
                                          REFERENCES app_user (app_user_id),

                                  CONSTRAINT fk_so_item_updated_by
                                      FOREIGN KEY (updated_by)
                                          REFERENCES app_user (app_user_id),

                                  CONSTRAINT ck_so_item_qty
                                      CHECK (
                                          ordered_qty > 0
                                              AND conversion_qty > 0
                                              AND base_ordered_qty > 0
                                              AND shipped_qty >= 0
                                              AND shipped_qty <= base_ordered_qty
                                          ),

                                  CONSTRAINT ck_so_item_amount
                                      CHECK (
                                          unit_price >= 0
                                              AND supply_amount >= 0
                                              AND tax_amount >= 0
                                              AND total_amount >= 0
                                          ),

                                  CONSTRAINT ck_so_item_tax_type
                                      CHECK (tax_type IN ('TAXABLE', 'TAX_FREE'))
);
