-- =========================================================
-- OUTBOUND : 출고 Header
-- 확정된 판매주문을 기준으로 만드는 출고 문서 표지
-- =========================================================
CREATE TABLE outbound (
                          outbound_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                          company_id NUMBER(19) NOT NULL,
                          outbound_no VARCHAR2(30 CHAR) NOT NULL,

    -- 단독 출고는 허용하지 않으므로 반드시 판매주문을 연결한다.
                          sales_order_id NUMBER(19) NOT NULL,
                          warehouse_id NUMBER(19) NOT NULL,

                          outbound_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                          status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                          memo VARCHAR2(1000 CHAR),

                          confirmed_at TIMESTAMP(6),
                          confirmed_by NUMBER(19),

    -- 출고취소는 삭제하지 않고 취소 정보와 상태를 남긴다.
                          cancelled_by NUMBER(19),
                          cancelled_at TIMESTAMP(6),
                          cancel_reason VARCHAR2(500 CHAR),

                          created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          created_by NUMBER(19) NOT NULL,
                          updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          updated_by NUMBER(19),

                          CONSTRAINT pk_outbound
                              PRIMARY KEY (outbound_id),

                          CONSTRAINT uq_outbound_company_no
                              UNIQUE (company_id, outbound_no),

                          CONSTRAINT fk_outbound_company
                              FOREIGN KEY (company_id)
                                  REFERENCES company (company_id),

                          CONSTRAINT fk_outbound_sales_order
                              FOREIGN KEY (sales_order_id)
                                  REFERENCES sales_order (sales_order_id),

                          CONSTRAINT fk_outbound_warehouse
                              FOREIGN KEY (warehouse_id)
                                  REFERENCES warehouse (warehouse_id),

                          CONSTRAINT fk_outbound_confirmed_by
                              FOREIGN KEY (confirmed_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_cancelled_by
                              FOREIGN KEY (cancelled_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_created_by
                              FOREIGN KEY (created_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT fk_outbound_updated_by
                              FOREIGN KEY (updated_by)
                                  REFERENCES app_user (app_user_id),

                          CONSTRAINT ck_outbound_status
                              CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);
