-- =========================================================
-- OUTBOUND_ITEM : 출고 품목
-- 출고 문서 안에서 실제로 어떤 주문 품목을 얼마나 출고하는지 저장
-- =========================================================
CREATE TABLE outbound_item (
                               outbound_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                               outbound_id NUMBER(19) NOT NULL,
                               line_no NUMBER(10) NOT NULL,

    -- 어떤 판매주문 품목을 출고하는지 연결
                               sales_order_item_id NUMBER(19) NOT NULL,

    -- 이번 출고에 선택한 거래단위
    -- 주문단위와 달라도 되지만, 같은 상품의 단위여야 함
    -- 이 관계 검증은 나중에 Service에서 처리
                               product_unit_id NUMBER(19) NOT NULL,

    -- 이번 출고의 거래단위 수량
                               shipped_qty NUMBER(19,3) NOT NULL,

    -- 이번 출고 당시의 단위 환산수량
                               conversion_qty NUMBER(19,3) NOT NULL,

    -- shipped_qty × conversion_qty
    -- 이번 출고의 기준단위 수량
                               base_shipped_qty NUMBER(19,3) NOT NULL,

                               created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               created_by NUMBER(19) NOT NULL,
                               updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               updated_by NUMBER(19),

                               CONSTRAINT pk_outbound_item
                                   PRIMARY KEY (outbound_item_id),

    -- 같은 출고서에서 품목 순번은 중복될 수 없다.
                               CONSTRAINT uq_outbound_item_line
                                   UNIQUE (outbound_id, line_no),

    -- 하나의 출고서에서 같은 판매주문 품목을 두 줄로 나누지 않는다.
                               CONSTRAINT uq_outbound_item_so_item
                                   UNIQUE (outbound_id, sales_order_item_id),

                               CONSTRAINT fk_outbound_item_outbound
                                   FOREIGN KEY (outbound_id)
                                       REFERENCES outbound (outbound_id),

                               CONSTRAINT fk_outbound_item_sales_order_item
                                   FOREIGN KEY (sales_order_item_id)
                                       REFERENCES sales_order_item (sales_order_item_id),

                               CONSTRAINT fk_outbound_item_product_unit
                                   FOREIGN KEY (product_unit_id)
                                       REFERENCES product_unit (product_unit_id),

                               CONSTRAINT fk_outbound_item_created_by
                                   FOREIGN KEY (created_by)
                                       REFERENCES app_user (app_user_id),

                               CONSTRAINT fk_outbound_item_updated_by
                                   FOREIGN KEY (updated_by)
                                       REFERENCES app_user (app_user_id),

                               CONSTRAINT ck_outbound_item_qty
                                   CHECK (
                                       shipped_qty > 0
                                           AND conversion_qty > 0
                                           AND base_shipped_qty > 0
                                       )
);
