-- =========================================================
-- OUTBOUND_ITEM_LOT : 출고 품목별 LOT 배정
-- LOT 관리상품일 때만 이 테이블에 행을 만든다.
-- =========================================================
CREATE TABLE outbound_item_lot (
                                   outbound_item_lot_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                   outbound_item_id NUMBER(19) NOT NULL,
                                   lot_id NUMBER(19) NOT NULL,

    -- 해당 LOT에서 실제로 출고하는 기준단위 수량
                                   base_lot_qty NUMBER(19,3) NOT NULL,

                                   created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                   created_by NUMBER(19) NOT NULL,
                                   updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                   updated_by NUMBER(19),

                                   CONSTRAINT pk_outbound_item_lot
                                       PRIMARY KEY (outbound_item_lot_id),

    -- 같은 출고 품목에서 같은 LOT를 두 번 선택할 수 없다.
                                   CONSTRAINT uq_outbound_item_lot
                                       UNIQUE (outbound_item_id, lot_id),

                                   CONSTRAINT fk_outbound_item_lot_outbound_item
                                       FOREIGN KEY (outbound_item_id)
                                           REFERENCES outbound_item (outbound_item_id),

                                   CONSTRAINT fk_outbound_item_lot_lot
                                       FOREIGN KEY (lot_id)
                                           REFERENCES lot (lot_id),

                                   CONSTRAINT fk_outbound_item_lot_created_by
                                       FOREIGN KEY (created_by)
                                           REFERENCES app_user (app_user_id),

                                   CONSTRAINT fk_outbound_item_lot_updated_by
                                       FOREIGN KEY (updated_by)
                                           REFERENCES app_user (app_user_id),

                                   CONSTRAINT ck_outbound_item_lot_qty
                                       CHECK (base_lot_qty > 0)
);

