-- =========================================================
-- STOCKTAKE : 재고실사 Header
-- 실사 문서의 기본정보와 확정 상태를 저장
-- =========================================================
CREATE TABLE stocktake (
                           stocktake_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                           company_id NUMBER(19) NOT NULL,
                           stocktake_no VARCHAR2(30 CHAR) NOT NULL,
                           warehouse_id NUMBER(19) NOT NULL,

                           stocktake_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                           status VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
                           memo VARCHAR2(1000 CHAR),

                           confirmed_at TIMESTAMP(6),
                           confirmed_by NUMBER(19),

                           created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                           created_by NUMBER(19) NOT NULL,
                           updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                           updated_by NUMBER(19),

                           CONSTRAINT pk_stocktake
                               PRIMARY KEY (stocktake_id),

                           CONSTRAINT uq_stocktake_company_no
                               UNIQUE (company_id, stocktake_no),

                           CONSTRAINT fk_stocktake_company
                               FOREIGN KEY (company_id)
                                   REFERENCES company (company_id),

                           CONSTRAINT fk_stocktake_warehouse
                               FOREIGN KEY (warehouse_id)
                                   REFERENCES warehouse (warehouse_id),

                           CONSTRAINT fk_stocktake_confirmed_by
                               FOREIGN KEY (confirmed_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT fk_stocktake_created_by
                               FOREIGN KEY (created_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT fk_stocktake_updated_by
                               FOREIGN KEY (updated_by)
                                   REFERENCES app_user (app_user_id),

                           CONSTRAINT ck_stocktake_status
                               CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);
