

-- =========================================================
-- STOCKTAKE_ITEM : 재고실사 품목
-- 상품 단위 또는 LOT 단위로 전산수량과 실제수량을 기록
-- =========================================================
CREATE TABLE stocktake_item (
                                stocktake_item_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                stocktake_id NUMBER(19) NOT NULL,
                                line_no NUMBER(10) NOT NULL,

                                product_id NUMBER(19) NOT NULL,

    -- LOT 관리상품: LOT ID 저장
    -- LOT 비관리상품: NULL
                                lot_id NUMBER(19),

    -- 전산상 수량 / 실제 센 수량 / 차이 수량
                                system_qty NUMBER(19,3) NOT NULL,
                                actual_qty NUMBER(19,3) NOT NULL,
                                difference_qty NUMBER(19,3) NOT NULL,

                                reason VARCHAR2(500 CHAR),

                                created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                created_by NUMBER(19) NOT NULL,
                                updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                updated_by NUMBER(19),

                                CONSTRAINT pk_stocktake_item
                                    PRIMARY KEY (stocktake_item_id),

                                CONSTRAINT uq_stocktake_item_line
                                    UNIQUE (stocktake_id, line_no),

    -- 같은 실사 문서에 같은 상품·같은 LOT를 중복 등록하지 않는다.
    -- LOT 비관리상품은 lot_id가 NULL인 상태로 적용한다.
                                CONSTRAINT uq_stocktake_item_product_lot
                                    UNIQUE (stocktake_id, product_id, lot_id),

                                CONSTRAINT fk_stocktake_item_stocktake
                                    FOREIGN KEY (stocktake_id)
                                        REFERENCES stocktake (stocktake_id),

                                CONSTRAINT fk_stocktake_item_product
                                    FOREIGN KEY (product_id)
                                        REFERENCES product (product_id),

                                CONSTRAINT fk_stocktake_item_lot
                                    FOREIGN KEY (lot_id)
                                        REFERENCES lot (lot_id),

                                CONSTRAINT fk_stocktake_item_created_by
                                    FOREIGN KEY (created_by)
                                        REFERENCES app_user (app_user_id),

                                CONSTRAINT fk_stocktake_item_updated_by
                                    FOREIGN KEY (updated_by)
                                        REFERENCES app_user (app_user_id),

                                CONSTRAINT ck_stocktake_item_qty
                                    CHECK (
                                        system_qty >= 0
                                            AND actual_qty >= 0
                                        )
);

