CREATE TABLE app_role (
                          app_role_id    NUMBER(19)
                   GENERATED BY DEFAULT ON NULL AS IDENTITY,

                          company_id     NUMBER(19)          NOT NULL,
                          role_code      VARCHAR2(50 CHAR)   NOT NULL,
                          role_name      VARCHAR2(100 CHAR)  NOT NULL,
                          role_type      VARCHAR2(20 CHAR)   NOT NULL,
                          description    VARCHAR2(200 CHAR),

                          use_yn         CHAR(1 CHAR)
    DEFAULT 'Y'         NOT NULL,

created_at     TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by     NUMBER(19),

updated_at     TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by     NUMBER(19),

CONSTRAINT pk_app_role
PRIMARY KEY (app_role_id),

CONSTRAINT fk_app_role_company
FOREIGN KEY (company_id)
REFERENCES company (company_id),

CONSTRAINT fk_app_role_created_by
FOREIGN KEY (created_by)
REFERENCES app_user (app_user_id),

CONSTRAINT fk_app_role_updated_by
FOREIGN KEY (updated_by)
REFERENCES app_user (app_user_id),

CONSTRAINT ck_app_role_type
CHECK (role_type IN ('OWNER', 'CUSTOM')),

CONSTRAINT ck_app_role_use_yn
CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_app_role_company_code
    ON app_role (
        company_id,
        LOWER(TRIM(role_code))
    );

CREATE UNIQUE INDEX uq_app_role_company_name
    ON app_role (
        company_id,
        LOWER(TRIM(role_name))
    );

CREATE UNIQUE INDEX uq_app_role_company_owner
    ON app_role (
        CASE
            WHEN role_type = 'OWNER'
            THEN company_id
        END
    );