CREATE TABLE app_permission
(
    app_permission_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    permission_code   VARCHAR2(80 CHAR)   NOT NULL,
    permission_name   VARCHAR2(100 CHAR)  NOT NULL,
    description       VARCHAR2(200 CHAR),

    created_at        TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_app_permission
        PRIMARY KEY (app_permission_id)
);

CREATE UNIQUE INDEX uq_app_permission_code_norm
    ON app_permission (
        LOWER(TRIM(permission_code))
    );