CREATE TABLE app_user_role
(
    app_user_role_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    app_user_id      NUMBER(19)    NOT NULL,
    app_role_id      NUMBER(19)    NOT NULL,

    active_yn        CHAR(1 CHAR)
    DEFAULT 'Y'   NOT NULL,

created_at         TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by         NUMBER(19),

updated_at         TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by         NUMBER(19),

CONSTRAINT pk_app_user_role
PRIMARY KEY (app_user_role_id),

CONSTRAINT fk_user_role_user
FOREIGN KEY (app_user_id)
REFERENCES app_user (app_user_id),

CONSTRAINT fk_user_role_role
FOREIGN KEY (app_role_id)
REFERENCES app_role (app_role_id),

CONSTRAINT fk_user_role_created_by
FOREIGN KEY (created_by)
REFERENCES app_user (app_user_id),

CONSTRAINT fk_user_role_updated_by
FOREIGN KEY (updated_by)
REFERENCES app_user (app_user_id),

CONSTRAINT uq_app_user_role
UNIQUE (app_user_id, app_role_id),

CONSTRAINT ck_user_role_active_yn
CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX ix_app_user_role_role
    ON app_user_role (app_role_id);