CREATE TABLE app_role_permission (
                                     app_role_permission_id   NUMBER(19)
                             GENERATED BY DEFAULT ON NULL AS IDENTITY,

                                     app_role_id              NUMBER(19)    NOT NULL,
                                     app_permission_id        NUMBER(19)    NOT NULL,

                                     active_yn                CHAR(1 CHAR)
    DEFAULT 'Y'   NOT NULL,

created_at               TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
created_by               NUMBER(19),

updated_at               TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,
updated_by               NUMBER(19),

CONSTRAINT pk_app_role_permission
PRIMARY KEY (app_role_permission_id),

CONSTRAINT fk_role_perm_role
FOREIGN KEY (app_role_id)
REFERENCES app_role (app_role_id),

CONSTRAINT fk_role_perm_permission
FOREIGN KEY (app_permission_id)
REFERENCES app_permission (app_permission_id),

CONSTRAINT fk_role_perm_created_by
FOREIGN KEY (created_by)
REFERENCES app_user (app_user_id),

CONSTRAINT fk_role_perm_updated_by
FOREIGN KEY (updated_by)
REFERENCES app_user (app_user_id),

CONSTRAINT uq_app_role_permission
UNIQUE (app_role_id, app_permission_id),

CONSTRAINT ck_role_perm_active_yn
CHECK (active_yn IN ('Y', 'N'))
);

CREATE INDEX ix_role_perm_permission
    ON app_role_permission (app_permission_id);