CREATE TABLE app_role_permission_history
(
    role_permission_history_id NUMBER(19)
        GENERATED BY DEFAULT ON NULL AS IDENTITY,

    app_role_permission_id     NUMBER(19)          NOT NULL,
    action_type                VARCHAR2(10 CHAR)   NOT NULL,
    change_reason              VARCHAR2(200 CHAR),
    change_source              VARCHAR2(10 CHAR)   NOT NULL,

    changed_at                 TIMESTAMP(6)
        DEFAULT SYSTIMESTAMP NOT NULL,
    changed_by                 NUMBER(19),

    CONSTRAINT pk_role_perm_history
        PRIMARY KEY (role_permission_history_id),

    CONSTRAINT fk_role_perm_hist_link
        FOREIGN KEY (app_role_permission_id)
            REFERENCES app_role_permission (app_role_permission_id),

    CONSTRAINT fk_role_perm_hist_user
        FOREIGN KEY (changed_by)
            REFERENCES app_user (app_user_id),

    CONSTRAINT ck_role_perm_hist_action
        CHECK (action_type IN ('GRANTED', 'REVOKED')),

    CONSTRAINT ck_role_perm_hist_source
        CHECK (change_source IN ('USER', 'SYSTEM')),

    CONSTRAINT ck_role_perm_hist_actor
        CHECK (
            (
                change_source = 'USER'
                    AND changed_by IS NOT NULL
                )
                OR
            (
                change_source = 'SYSTEM'
                    AND changed_by IS NULL
                )
            )
);

CREATE INDEX ix_role_perm_hist_link
    ON app_role_permission_history (
        app_role_permission_id,
        changed_at
    );

CREATE INDEX ix_role_perm_hist_user
    ON app_role_permission_history (
        changed_by,
        changed_at
    );