CREATE TABLE unit
(
    unit_id     NUMBER(19)
                  GENERATED BY DEFAULT ON NULL AS IDENTITY,

    unit_code   VARCHAR2(20 CHAR)   NOT NULL,
    unit_name   VARCHAR2(50 CHAR)   NOT NULL,
    description VARCHAR2(200 CHAR),

    use_yn      CHAR(1 CHAR
)
    DEFAULT 'Y'         NOT NULL,

created_at    TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,

updated_at    TIMESTAMP(6)
    DEFAULT SYSTIMESTAMP NOT NULL,

CONSTRAINT pk_unit
PRIMARY KEY (unit_id),

CONSTRAINT ck_unit_use_yn
CHECK (use_yn IN ('Y', 'N'))
);

CREATE UNIQUE INDEX uq_unit_code_norm
    ON unit (
        LOWER(TRIM(unit_code))
    );