spring:
  application:
    name: food-logistics-erp


  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

logging:
  file:
    path: ${LOG_PATH:logs}